services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    user: root
    command: postgres -c shared_preload_libraries=timescaledb
    container_name: timescaledb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    networks:
      - timescaledb
  timescaledb-fill:
    build: ./
    user: root
    image: filldb
    networks:
      - timescaledb
    depends_on:
      - timescaledb

volumes:
  timescale_data:

networks:
  timescaledb:
    name: timescaledb_network